services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data/
      - ./pgsql-script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"